export const ERROR = "ERROR";

export const GETTING_USERS = "GETTING_USERS";
export const GOT_USERS = "GOT_USERS";
export const GETTING_SINGLE_USER = "GETTING_SINGLE_USER";
export const GOT_SINGLE_USER = "GOT_SINGLE_USER";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_UPDATING = "USER_UPDATING";
export const USER_UPDATE_COMPLETE = "USER_UPDATE_COMPLETE";

export const TOGGLE_UPDATE_USER_FORM = "TOGGLE_UPDATE_USER_FORM";

export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const CHECK_IF_AUTHENTICATED = "CHECK_IF_AUTHENTICATED";
export const USER_UNAUTHENTICATED = "USER_UNAUTHENTICATED";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR" ;

export const SETTING_APPOINTMENT = "SETTING_APPOINTMENT";
export const APPOINTMENT_SET = "APPOINTMENT_SET";
export const GETTING_APPOINTMENTS = "GETTING_APPOINTMENT";
export const APPOINTMENTS_GOT = "APPOINTMENTS_GOT";

export const STYLIST_UPDATING = "STYLIST_UPDATING";
export const STYLIST_UPDATE_COMPLETE = "STYLIST_UPDATE_COMPLETE";
export const TOGGLE_UPDATE_STYLIST_FORM = "TOGGLE_UPDATE_STYLIST_FORM";
export const GETTING_STYLISTS = "GETTING_STYLISTS";
export const GOT_STYLISTS = "GOT_STYLISTS";

export const GETTING_SERVICES = "SETTING_SERVICES";
export const SERVICES_GOT = "SERVICE_SET";

export const CREATING_FEEDBACK = "CREATING_FEEDBACK";
export const FEEDBACK_CREATED = "FEEDBACK_CREATED";
export const TOGGLE_FEEDBACK_FORM = "TOGGLE_FEEDBACK_FORM";
